### ISSUE TITLE
Meditation activity type

### ISSUE THREAD

**Issue by louwers** [dliedke/MeditateInstinct2#1]
Can you apply a similar patch as https://github.com/dliedke/Meditate/commit/ac6cba1d3f0a3ed818ff096433ae9cdb4aeab003 to use the new Meditation activity type.

Thanks for making this app. 🙏

**Comment by dliedke** [comment]
Sure, I will work on that and let you know when finished so you can test it. Thanks a lot! 😃

**Comment by louwers** [comment]
Perfect!

**Comment by dliedke** [comment]
Hello,

Version 3.6.0 was published with Meditate activity type at:

https://apps.garmin.com/en-US/apps/45829a6e-f247-4261-9ae6-8587f557f397

Garmin note: Please note: This app has a version update pending. Changes will not be visible until the approval is complete. This process could take up to 2 hours.

Please test in your physical device and let me know the results. I don't own any Garmin Instinct watch but it worked in the simulator here.

Thank you!

Daniel

**Comment by louwers** [comment]
Cool. I will try it out when it is online.

I also managed to set up the Garmin development environment, build & run an app (both in a simulator and on my device).

When I tried to use MeditateInstinct2 before:

- I didn't like the buzz every 5 minutes. Is it configurable?
- At the end of the session, the buzz was not very pronounced (I think I missed it completely).
- When I tried to save, I got an error. It still saved OK though.

I don't know anything about Monkey C and Garmin development yet, but I'm interested in having an app available for my watch that suits my needs. I tried out [this other app](https://github.com/aiMonster/Garmin-Meditate/) as well.

Thank you too.

Bart

**Comment by dliedke** [comment]
Nice that you could run the app in your machine! Congrats!

>I didn't like the buzz every 5 minutes. Is it configurable?

Not really, the app memory space for Instinct 2 watches is small.
In Alert class reset() method you have this setup in file
https://github.com/dliedke/MeditateInstinct2/blob/main/Meditate/source/activity/IntervalAlerts.mc

>At the end of the session, the buzz was not very pronounced (I think I missed it completely).

This can be changed, in getLongContinuous() method in file https://github.com/dliedke/MeditateInstinct2/blob/main/Meditate/source/activity/VibeAlertsExecutor.mc

>When I tried to save, I got an error. It still saved OK though.

Yes, other people reported that but I have no clue why. Maybe with the physical device compiling in debug mode you may find the issue in the logs at /GARMIN/APPS/LOGS and we can fix it.

Some links to help you below. Also GPT-4 knows a bit of Monkey C, sometimes hallucinate as usual but can guide you.

Garmin Devices:
https://developer.garmin.com/connect-iq/compatible-devices/

Connect IQ basics:
https://developer.garmin.com/connect-iq/connect-iq-basics/

Toybox API:
https://developer.garmin.com/connect-iq/api-docs/

Thanks!
