### ISSUE TITLE
Question about the frequency of stress sampling on Instinct2

### ISSUE THREAD

**Issue by robcsi** [dliedke/MeditateInstinct2#2]
I noticed that the Instinct2 version collects stress data more rarely than the non-Instinct version.
My Forerunner has a very continuous graph in the activity, whereas on my Instinct2 the graph has gaps.

Instinct2:
![image](https://github.com/user-attachments/assets/6e57e4c9-534e-46ad-82d4-c38ed29e3476)

Forerunner:
![image](https://github.com/user-attachments/assets/d4efa252-837d-4ebe-80d5-5b55cf3651fe)

Is this also related to the memory limit of the watch compared to other more capable watches?

**Comment by robcsi** [comment]
I also noticed that on the Instinct2 on the gaps it shows very low stress values, which is interesting...
That never happens in the Forerunner meditation activities, even when stress levels are that low.

**Comment by dliedke** [comment]
Hello, I am sorry but stress data is collected automatically by the watch itself and not the app. The Meditate app for Instict2 is only saving HR data to create the HR chart later. All other data is native from the activity and the watch. 
Thanks,
Daniel

**Comment by robcsi** [comment]
No problem, I don't mean to make accusations, just trying to figure out why this happens.

I thought stress data and any other data type shown in the activity is measured by the app.

Then it means the Instinct 2 gathers stress data less often.

Thanks for clarifying.
